/**
 * Dynamically resolves the Hindi / Custom Title Logo image URL from itinerary heroMedia.
 *
 * @param {Object} itinerary
 * @returns {string|null}
 */
export function resolveHindiLogo(itinerary) {
  if (!itinerary) return null;
  const heroMedia = itinerary.heroMedia || itinerary.commondetails?.heroMedia;
  const logo = heroMedia?.logoUrl || heroMedia?.hindiLogoUrl || heroMedia?.logoUrlEnglish || itinerary.logoUrl || null;
  if (typeof logo === 'string' && logo.trim()) return logo.trim();
  if (typeof logo === 'object' && logo.url) return logo.url.trim();
  return null;
}

/**
 * Dynamically resolves the hero cover image URL from any API property format.
 *
 * @param {Object} itinerary
 * @returns {string|null}
 */
export function resolveHeroImage(itinerary) {
  if (!itinerary) return null;
  const resolve = (img) => {
    if (!img) return null;
    if (typeof img === 'string' && img.trim()) return img.trim();
    if (typeof img === 'object') {
      return img.url || img.heroImage || img.bannerUrl || img.imageUrl || img.src || img.image || img.path || null;
    }
    return null;
  };

  const candidates = [
    resolve(itinerary.heroMedia),
    resolve(itinerary.heroMedia?.url),
    resolve(itinerary.heroMedia?.heroImage),
    resolve(itinerary.heroMedia?.bannerUrl),
    resolve(itinerary.heroMedia?.imageUrl),
    resolve(itinerary.bannerImage),
    resolve(itinerary.heroImage),
    resolve(itinerary.heroImageUrl),
    resolve(itinerary.bannerUrl),
    resolve(itinerary.coverImage),
    resolve(itinerary.image),
    resolve(itinerary.featuredImage),
    resolve(itinerary.gallery?.find((g) => typeof g === 'object' && g?.tag === 'banner')),
    ...(Array.isArray(itinerary.gallery) ? itinerary.gallery.map(resolve) : []),
    ...(Array.isArray(itinerary.images) ? itinerary.images.map(resolve) : []),
  ].filter((url, idx, self) => typeof url === 'string' && url.trim() !== '' && self.indexOf(url) === idx);

  return candidates[0] || null;
}

/**
 * Sanitizes input text to prevent XSS and ensure safe PDF rendering.
 *
 * @param {any} input
 * @returns {string}
 */
export function sanitizeText(input) {
  if (input === null || input === undefined) return '';
  let text = '';
  if (typeof input === 'object') {
    text = input.name || input.title || input.text || input.description || input.label || input.value || '';
  } else {
    text = String(input);
  }

  text = text.replace(/<[^>]*>/g, ' ');
  text = text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ');

  text = text.replace(/[\r\v\f]/g, '').replace(/[^\x20-\x7E\n\u00A0-\u024F]/g, ' ');

  return text
    .split('\n')
    .map((line) => line.trim().replace(/\s+/g, ' '))
    .join('\n')
    .trim();
}

/**
 * Triggers the download of the pristine server-rendered PDF generated by Puppeteer.
 * Avoids any main-thread client-side canvas compilation, eliminating UI freezing.
 *
 * @param {Object} itinerary
 */
export async function generateItineraryPdf(itinerary) {
  if (!itinerary || typeof window === 'undefined') return;

  const rawTitle = itinerary.title || 'Meghalaya Expedition';
  const cleanTitle = sanitizeText(rawTitle);
  const slug = itinerary.slug || 'meghalaya-expedition';
  const filename = `${cleanTitle.replace(/[^a-zA-Z0-9]/g, '_')}_Encamp_Prive.pdf`;

  const res = await fetch(`/api/pdf/${slug}`, { cache: 'no-store' });

  if (!res.ok) {
    const errorText = await res.text().catch(() => '');
    throw new Error(`PDF generation failed with status ${res.status}: ${errorText}`);
  }

  const blob = await res.blob();
  const blobUrl = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.style.display = 'none';
  link.href = blobUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();

  setTimeout(() => {
    if (link.parentNode) {
      link.parentNode.removeChild(link);
    }
    window.URL.revokeObjectURL(blobUrl);
  }, 1000);
}
